name: Deploy Web to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'
          
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Build Web
        # Dynamically set base-href to repository name for correct routing on GH Pages
        run: flutter build web --release --base-href "/$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')/"

      - name: Copy index.html to 404.html for SPA routing
        run: cp build/web/index.html build/web/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
